### ISSUE TITLE
Low performance due to width/height animation

### ISSUE THREAD

**Issue by marcinlichwala** [ROUND/enhance.js#1]
https://github.com/ROUND/enhance.js/blob/master/js/enhance.js#L199-L203

The whole benefit of using Velocity.js is effectively killed by animating the paint/layout-triggering CSS properties.

Should be changed to transform-based animations only.

Good read: https://aerotwist.com/blog/flip-your-animations/

**Comment by round** [comment]
Unfortunately, the only way to achieve dynamic image cropping is to transition the dimensional values of the image element.

But, you are right – on elements where the `img` is being resized there is a an approximate increase of 300% in paint time.

Any ideas on how to overcome this?
