### ISSUE TITLE
Doesn't work on Mac Safari

### ISSUE THREAD

**Issue by ckizer** [ROUND/enhance.js#2]
Doesn't work on Mac Safari browser. Tested on Mavericks, Yosemite 10.10, and Yosemite 10.11 latest.

**Comment by round** [comment]
Thanks for the bug report! I've tested with these setups and it seems to work (although performance leaves something to be desired)…

Any chance you could share a quick screen recording or check the JS console for me?

**Comment by round** [comment]
@ckizer bump
